/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Charge.java
 *
 * Created on Apr 17, 2013, 10:49:19 AM
 */
package hmdi;

import java.sql.*;
import java.text.*;
import dao.Database;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.Vector;
import javax.swing.JList;
import javax.swing.JOptionPane;
import sun.org.mozilla.javascript.internal.ast.SwitchCase;

/**
 *
 * @author Tonu
 */
public class Charge extends javax.swing.JInternalFrame {

    /** Creates new form Charge */
    public Charge() {
        initComponents();
        loadComboR();
        loadCombo();
        CDate();
    }
    String Fn, Ln, Rno, Day, Mon, Year, Cdate, Citm, Pri;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbmRn = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        txtFN = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtLN = new javax.swing.JTextField();
        cbmCa = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtDay2 = new javax.swing.JTextField();
        txtMon2 = new javax.swing.JTextField();
        txtYear2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Charge");

        jPanel5.setBackground(new java.awt.Color(240, 250, 242));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setText("Room No :");

        cbmRn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmRnItemStateChanged(evt);
            }
        });
        cbmRn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmRnActionPerformed(evt);
            }
        });

        jLabel26.setText("Categori :");

        jLabel18.setText("First Name :");

        jLabel23.setText("Last Name :");

        cbmCa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmCaItemStateChanged(evt);
            }
        });
        cbmCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmCaActionPerformed(evt);
            }
        });

        jLabel9.setText("Date :");

        jLabel3.setText("Year");

        jLabel2.setText("Month");

        jLabel1.setText("Day");

        jLabel4.setText("Price :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel26)
                    .addComponent(jLabel18)
                    .addComponent(jLabel23)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtDay2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMon2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbmCa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLN)
                    .addComponent(txtFN)
                    .addComponent(cbmRn, 0, 164, Short.MAX_VALUE)
                    .addComponent(txtPrice))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbmRn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cbmCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 204, 255));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CDate() {
        Date dat = new Date();
        DateFormat df = new SimpleDateFormat("dd");
        DateFormat df1 = new SimpleDateFormat("MM");
        DateFormat df2 = new SimpleDateFormat("yyyy");
        txtDay2.setText(df.format(dat));
        txtMon2.setText(df1.format(dat));
        txtYear2.setText(df2.format(dat));
    }

    private void loadCombo() {

        String rType[] = {"Food Bill", "Service Bill", "Other Bill"};

        cbmCa.setModel(new javax.swing.DefaultComboBoxModel(rType));
        cbmCa.insertItemAt("--Select--", 0);
        cbmCa.setSelectedIndex(0);

    }

    private void loadComboR() {
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            conn = Database.getConnection();
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select room_no from customer_info order by room_no");

            List plist = new ArrayList();
            while (rs.next()) {
                plist.add(rs.getString("room_no"));
            }
            cbmRn.setModel(new javax.swing.DefaultComboBoxModel(plist.toArray()));
            cbmRn.insertItemAt("--Select--", 0);
            cbmRn.setSelectedIndex(0);
        } catch (Exception e1) {
            e1.printStackTrace();
        }

    }

    private void getAllRecords() {
        Fn = txtFN.getText();
        Ln = txtLN.getText();
        Pri = txtPrice.getText().toString();
        Rno = cbmRn.getSelectedItem().toString();
        Day = txtDay2.getText().toString();
        Mon = txtMon2.getText().toString();
        Year = txtYear2.getText().toString();

    }
private void cbmRnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmRnItemStateChanged
// TODO add your handling code here:
    if (cbmRn.getSelectedIndex() > 0) {
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            conn = Database.getConnection();
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select * from customer_info where room_no = '" + cbmRn.getSelectedItem().toString() + "'");
            while (rs.next()) {
                txtFN.setText(rs.getString("first_name"));
                txtLN.setText(rs.getString("last_name"));
            }
        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }
}//GEN-LAST:event_cbmRnItemStateChanged

    private void clear() {
        cbmRn.setSelectedIndex(0);
        txtFN.setText("");
        txtLN.setText("");
        cbmCa.setSelectedIndex(0);

    }

    public void setDate() {
        Cdate = Year + "-" + Mon + "-" + Day;
    }
private void cbmRnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmRnActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cbmRnActionPerformed

private void cbmCaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmCaItemStateChanged
// TODO add your handling code here:
}//GEN-LAST:event_cbmCaItemStateChanged

private void cbmCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmCaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cbmCaActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
// TODO add your handling code here:
    int c = cbmCa.getSelectedIndex();
    if(c > 0){
    double foo = 0;
    double ser = 0;
    double oth = 0;
    Connection con = null;
    Statement stm = null;

    getAllRecords();
    setDate();
    switch (c) {
        case 1:
            try {
                con = Database.getConnection();
                stm = con.createStatement();
                stm.executeUpdate( "insert into charge_info (first_name, last_name, room_no, food_bill, service_bill, other_bill, date) values ('" + Fn + "','" + Ln + "','" + Rno + "','" + Pri + "','" + ser + "','" + oth + "','" + Cdate + "');" );
                JOptionPane.showMessageDialog(rootPane, "Charge Inserted");
                break;
            } catch (Exception e1) {
                e1.printStackTrace();
            }

        case 2:
            try {
                con = Database.getConnection();
                stm = con.createStatement();
                stm.executeUpdate( "insert into charge_info (first_name, last_name, room_no, food_bill, service_bill, other_bill, date) values ('" + Fn + "','" + Ln + "','" + Rno + "','" + foo + "','" + Pri + "','" + oth + "','" + Cdate + "');" );
                JOptionPane.showMessageDialog(rootPane, "Charge Inserted");
                break;
            } catch (Exception e1) {
                e1.printStackTrace();
            }

        case 3:
            try {
                con = Database.getConnection();
                stm = con.createStatement();
                stm.executeUpdate("insert into charge_info (first_name, last_name, room_no, food_bill, service_bill, other_bill, date) values ('" + Fn + "','" + Ln + "','" + Rno + "','" + foo + "','" + ser + "','" + Pri + "','" + Cdate + "');");
                JOptionPane.showMessageDialog(rootPane, "Charge Inserted");
                break;
            } catch (Exception e1) {
                e1.printStackTrace();
            }

        default:
            break;
    }
    clear();
    }else {
        JOptionPane.showMessageDialog(rootPane, "Please select Room No.");
    }
}//GEN-LAST:event_btnOkActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    clear();
}//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cbmCa;
    private javax.swing.JComboBox cbmRn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtDay2;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtLN;
    private javax.swing.JTextField txtMon2;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtYear2;
    // End of variables declaration//GEN-END:variables
}
