/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewReservation.java
 *
 * Created on Apr 6, 2013, 9:56:10 PM
 */
package hmdi;

import dao.Database;
import java.sql.*;
import java.text.*;
import dao.Database;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.Vector;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Tonu
 */
public class CheckIn extends javax.swing.JInternalFrame {

    /** Creates new form NewReservation */
    public CheckIn() {
        initComponents();
        loadCombo();
        loadComboR();
        CDate();
    }
    String Fn, Ln, Adr, Ph, Em, Id, Rty, Rno, Day, Mon, Year, Adate, Gen;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtFN = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtLN = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtDay2 = new javax.swing.JTextField();
        txtMon2 = new javax.swing.JTextField();
        txtYear2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtList = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbmItem = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbmItem1 = new javax.swing.JComboBox();
        txtRty1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Check In");

        jPanel6.setBackground(new java.awt.Color(102, 204, 255));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(240, 250, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel18.setText("First Name :");

        jLabel19.setText("Address :");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane4.setViewportView(txtAddress);

        jLabel20.setText("Phone :");

        jLabel21.setText("Email :");

        jLabel22.setText("ID / Passport : ");

        jLabel23.setText("Last Name :");

        jLabel24.setText("Gender :");

        buttonGroup1.add(rbMale);
        rbMale.setSelected(true);
        rbMale.setText("Male");

        buttonGroup1.add(rbFemale);
        rbFemale.setText("Female");

        jLabel9.setText("Current Date :");

        jLabel1.setText("Day");

        jLabel2.setText("Month");

        jLabel3.setText("Year");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbFemale))
                            .addComponent(txtFN, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(txtLN)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel9))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(txtDay2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMon2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(rbMale)
                    .addComponent(rbFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(240, 250, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("New Check In"));

        jScrollPane2.setViewportView(txtList);

        jLabel7.setText("Room No :");

        jLabel6.setText("Room Type :");

        cbmItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Single", "Double", "Triple" }));
        cbmItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmItemItemStateChanged(evt);
            }
        });
        cbmItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbmItem, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)))
                .addGap(148, 148, 148))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbmItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(240, 250, 242));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Reserved Room Info"));

        jLabel8.setText("Room No :");

        jLabel10.setText("Room Type :");

        cbmItem1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmItem1ItemStateChanged(evt);
            }
        });
        cbmItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmItem1ActionPerformed(evt);
            }
        });

        jLabel26.setText("Reservation Date :");

        jLabel4.setText("Ignor this part if you selected room from the above");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbmItem1, 0, 187, Short.MAX_VALUE)
                            .addComponent(txtRty1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                .addGap(81, 81, 81))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbmItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CDate() {
        Date dat = new Date();
        DateFormat df = new SimpleDateFormat("dd");
        DateFormat df1 = new SimpleDateFormat("MM");
        DateFormat df2 = new SimpleDateFormat("yyyy");
        txtDay2.setText(df.format(dat));
        txtMon2.setText(df1.format(dat));
        txtYear2.setText(df2.format(dat));
    }

    public void setDate() {

        Adate = Year + "-" + Mon + "-" + Day;

    }

    public void getAllRecords() {
        Fn = txtFN.getText();
        Ln = txtLN.getText();
        Ph = txtPhone.getText();
        Adr = txtAddress.getText();
        Em = txtEmail.getText();
        Id = txtID.getText();
        Rty = cbmItem.getSelectedItem().toString();
        Rno = txtList.getSelectedValue().toString();
        Day = txtDay2.getText().toString();
        Mon = txtMon2.getText().toString();
        Year = txtYear2.getText().toString();

        if (rbMale.isSelected()) {
            Gen = "Male";
        } else {
            Gen = "Female";
        }

    }

    public void getAllRecordsR() {
        Fn = txtFN.getText();
        Ln = txtLN.getText();
        Ph = txtPhone.getText();
        Adr = txtAddress.getText();
        Em = txtEmail.getText();
        Id = txtID.getText();
        Rno = cbmItem1.getSelectedItem().toString();
        Rty = txtRty1.getText().toString();
        Day = txtDay2.getText().toString();
        Mon = txtMon2.getText().toString();
        Year = txtYear2.getText().toString();

        if (rbMale.isSelected()) {
            Gen = "Male";
        } else {
            Gen = "Female";
        }

    }

    public void loadCombo() {

        String rType[] = {"Single", "Double", "Triple"};

        cbmItem.setModel(new javax.swing.DefaultComboBoxModel(rType));
        cbmItem.insertItemAt("--Select--", 0);
        cbmItem.setSelectedIndex(0);

    }

    public void loadComboR() {
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            conn = Database.getConnection();
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select room_no from reservation_info order by room_no");

            List plist = new ArrayList();
            while (rs.next()) {
                plist.add(rs.getString("room_no"));
            }
            cbmItem1.setModel(new javax.swing.DefaultComboBoxModel(plist.toArray()));
            cbmItem1.insertItemAt("--Select--", 0);
            cbmItem1.setSelectedIndex(0);
        } catch (Exception e1) {
            e1.printStackTrace();
        }

    }

    public void clear() {
        txtFN.setText("");
        txtLN.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        txtEmail.setText("");
        cbmItem.setSelectedIndex(0);
        cbmItem1.setSelectedIndex(0);
        txtRty1.setText("");
        txtDate.setText("");
        txtID.setText("");

    }

private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
// TODO add your handling code here:
    Main m = new Main();
    double tfb = 0, tsb = 0, tob = 0, trb = 0, tpb = 0;
    String nod = "0";

    int c = cbmItem1.getSelectedIndex();
    if (c > 0) {
        getAllRecordsR();
    } else {
        getAllRecords();
    }

    setDate();
    if (txtFN.getText().isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "Please Enter First Name");
        txtFN.requestFocus();
    } else if (txtLN.getText().isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "Please Enter Last Name");
        txtLN.requestFocus();
    } else {
        if (txtAddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter the Address");
            txtAddress.requestFocus();
        } else {
            if (txtPhone.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please Enter Phone no");
                txtPhone.requestFocus();
            } else {
                if (emailValidity()) {                  
                   // txtEmail.requestFocus();

                } else {
                    if (txtID.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(rootPane, "Please Enter ID/passport");
                        txtID.requestFocus();
                    } else {
                        try {
                            String Occu = "Occupied";
                            Connection con = null;
                            Statement stm = null;
                            con = Database.getConnection();
                            stm = con.createStatement();

                            stm.executeUpdate("update room_info set Status='" + Occu + "' where room_no = '" + txtList.getSelectedValue() + "'");
                            stm.executeUpdate("insert into customer_info (first_name, last_name, gender, address, arrival_date, room_no, room_type, phone_no, id_passport, email_adr, total_food_bill, total_service_bill, total_other_bill, total_bill_paid ) values ('" + Fn + "','" + Ln + "','" + Gen + "','" + Adr + "','" + Adate + "','" + Rno + "','" + Rty + "','" + Ph + "','" + Id + "','" + Em + "','" + tfb + "','" + tsb + "','" + tob + "','" + tpb + "');");
                            stm.executeUpdate("insert into total_info (first_name, last_name, gender, address, arrival_date, room_no, room_type, phone_no, email_adr, total_food_bill, total_service_bill, total_other_bill, total_bill_paid, no_of_days, total_room_bill, departure_date ) values ('" + Fn + "','" + Ln + "','" + Gen + "','" + Adr + "','" + Adate + "','" + Rno + "','" + Rty + "','" + Ph + "','" + Em + "','" + tfb + "','" + tsb + "','" + tob + "','" + tpb + "','" + nod + "','" + trb + "','" + Adate + "');");
                            stm.executeUpdate("DELETE FROM reservation_info where room_no = '" + cbmItem1.getSelectedItem().toString() + "'");

                            JOptionPane.showMessageDialog(rootPane, "Check In successfull");
                            clear();
                            m.showTable1();


                        } catch (Exception e1) {
                            e1.printStackTrace();
                        }
                    }
                }
            }
        }
    }
}//GEN-LAST:event_btnOkActionPerformed

    public boolean emailValidity() {
        String em = txtEmail.getText().toString();
        if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter Email address");
            txtEmail.requestFocus();
            return true;
        } else {
            if (em.indexOf("@") == -1) {
                JOptionPane.showMessageDialog(rootPane, "Invalid Email");
                 txtEmail.requestFocus();
                return true;
            } else {
                if (em.indexOf(".com") == -1) {
                    JOptionPane.showMessageDialog(rootPane, "Invalid Email");
                     txtEmail.requestFocus();
                    return true;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Email is Valid");
                    txtID.requestFocus();
                    return true;
                }
            }
        }
    }

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void cbmItem1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmItem1ItemStateChanged
// TODO add your handling code here:
    if (cbmItem1.getSelectedIndex() > 0) {
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            conn = Database.getConnection();
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select * from reservation_info where room_no = '" + cbmItem1.getSelectedItem().toString() + "'");
            while (rs.next()) {
                txtRty1.setText(rs.getString("room_type"));
                txtDate.setText(rs.getString("reservation_date"));
                txtFN.setText(rs.getString("first_name"));
                txtLN.setText(rs.getString("last_name"));
                txtPhone.setText(rs.getString("phone_no"));
                txtAddress.setText(rs.getString("address"));
                txtEmail.setText(rs.getString("email_adr"));
                txtID.setText(rs.getString("id_passport"));

            }

        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }
}//GEN-LAST:event_cbmItem1ItemStateChanged

private void cbmItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmItem1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cbmItem1ActionPerformed

private void cbmItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmItemItemStateChanged
// TODO add your handling code here:

    if (evt.getStateChange() == ItemEvent.SELECTED) {

        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;
        Vector vec;
        vec = new Vector();

        try {
            con = Database.getConnection();
            stm = con.createStatement();
            rs = stm.executeQuery("Select room_no from room_info where status='Vacant' and room_type = '" + cbmItem.getSelectedItem().toString() + "' ");

            while (rs.next()) {
                boolean b = vec.add(rs.getInt("room_no"));
            }
            txtList.setListData(vec);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
}//GEN-LAST:event_cbmItemItemStateChanged

private void cbmItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmItemActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cbmItemActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    clear();
}//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbmItem;
    private javax.swing.JComboBox cbmItem1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDay2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLN;
    private javax.swing.JList txtList;
    private javax.swing.JTextField txtMon2;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRty1;
    private javax.swing.JTextField txtYear2;
    // End of variables declaration//GEN-END:variables
}
