/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CheckOut.java
 *
 * Created on May 16, 2013, 9:58:22 PM
 */
package hmdi;

import java.sql.*;
import java.text.*;
import dao.Database;
import dao.Database1;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.Vector;
import javax.swing.JList;
import javax.swing.JOptionPane;
import sun.org.mozilla.javascript.internal.ast.SwitchCase;

/**
 *
 * @author Tonu
 */
public class CheckOut extends javax.swing.JInternalFrame {

    private Main m;

    /** Creates new form CheckOut */
    public CheckOut() {
        initComponents();
        loadComboR();
        m = new Main();

    }
    String Fn, Ln, Adr, Rno, Rty, Ph, Em, Day, Mon, Year, Cdate, Adate, Citm, Pri, day, month, year, Td, Rb, Tf, Ts, To, Tp;
    int Ad, Dd, Am, Dm, y, y2, d3, y3, m3;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbmRn = new javax.swing.JComboBox();
        txtFN = new javax.swing.JTextField();
        txtLN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDay2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMon2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtYear2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        txtMon = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblTD = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblRPN = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblFB = new javax.swing.JLabel();
        lblSB = new javax.swing.JLabel();
        lblRB = new javax.swing.JLabel();
        lblOB = new javax.swing.JLabel();
        lblTO = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtPaid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblDue = new javax.swing.JLabel();
        btnPaid = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setTitle("Check Out");

        jPanel1.setBackground(new java.awt.Color(240, 250, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer info"));

        jLabel8.setText("Room No :");

        jLabel18.setText("First Name :");

        jLabel23.setText("Last Name :");

        cbmRn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmRnItemStateChanged(evt);
            }
        });
        cbmRn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmRnActionPerformed(evt);
            }
        });

        jLabel9.setText("Departure Date :");

        jLabel1.setText("Day");

        jLabel2.setText("Month");

        jLabel3.setText("Year");

        jLabel5.setText("Arrival Date :");

        txtMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonActionPerformed(evt);
            }
        });

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        jLabel12.setText("Total No of Days :");

        jLabel13.setText("Rate per night :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addComponent(jLabel18)
                                .addComponent(jLabel8))
                            .addGap(63, 63, 63)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLN, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(txtFN, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(cbmRn, 0, 213, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(133, 133, 133)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDay, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                        .addComponent(txtDay2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(31, 31, 31)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel2)
                                    .addGap(47, 47, 47)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtMon, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMon2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(txtYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRPN, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(49, 49, 49)
                                .addComponent(lblTD, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbmRn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(lblRPN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblTD, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnOk.setText("Check Out");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(25, 25, 25))
        );

        jPanel3.setBackground(new java.awt.Color(240, 250, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill info"));

        jLabel4.setText("Room Bill :");

        jLabel6.setText("Food Bill :");

        jLabel7.setText("Service Bill :");

        jLabel10.setText("Other Bill :");

        jLabel11.setText("Total to paid :");

        lblFB.setText("0000.00");

        lblSB.setText("0000.00");

        lblRB.setText("0000.00");

        lblOB.setText("0000.00");

        lblTO.setText("0000.00");

        jLabel20.setText("-----------------------------------------------------------------");

        jLabel21.setText("Paid :");

        txtPaid.setToolTipText("Amount tk.");

        jLabel14.setText("------------------------------------------------------------------");

        jLabel15.setText("Due :");

        btnPaid.setText("Paid");
        btnPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaidActionPerformed(evt);
            }
        });

        btnPrint.setText("Print");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPaid)
                .addGap(38, 38, 38)
                .addComponent(btnPrint)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel11))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(lblTO, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(txtPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel15)
                        .addGap(104, 104, 104)
                        .addComponent(lblDue, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(lblRB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblTO, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblDue, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(btnPaid))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CDate() {
        Date date = new Date();
        DateFormat df = new SimpleDateFormat("dd");
        DateFormat df1 = new SimpleDateFormat("MM");
        DateFormat df2 = new SimpleDateFormat("yyyy");
        txtDay2.setText(df.format(date));
        txtMon2.setText(df1.format(date));
        txtYear2.setText(df2.format(date));

    }

    private void loadComboR() {
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            conn = Database.getConnection();
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select room_no from customer_info order by room_no");

            List plist = new ArrayList();
            while (rs.next()) {
                plist.add(rs.getString("room_no"));
            }
            cbmRn.setModel(new javax.swing.DefaultComboBoxModel(plist.toArray()));
            cbmRn.insertItemAt("--Select--", 0);
            cbmRn.setSelectedIndex(0);
        } catch (Exception e1) {
            e1.printStackTrace();
        }

    }

    private void getAllRecords() {
        Fn = txtFN.getText();
        Ln = txtLN.getText();
        Rno = cbmRn.getSelectedItem().toString();
        Ad = Integer.parseInt(txtDay.getText());
        Am = Integer.parseInt(txtMon.getText());
        y = Integer.parseInt(txtYear.getText());
        Dd = Integer.parseInt(txtDay2.getText());
        Dm = Integer.parseInt(txtMon2.getText());
        y2 = Integer.parseInt(txtYear2.getText());
        Td = lblTD.getText().toString();
        Rb = lblRB.getText().toString();
        Tf = lblFB.getText().toString();
        Ts = lblSB.getText().toString();
        To = lblOB.getText().toString();
        Tp = txtPaid.getText().toString();

    }

    private void clear() {
        cbmRn.setSelectedIndex(0);
        txtFN.setText("");
        txtLN.setText("");


    }

    public void setDate() {
        Cdate = Year + "-" + Mon + "-" + Day;
    }

private void cbmRnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmRnItemStateChanged
// TODO add your handling code here:
    if (cbmRn.getSelectedIndex() > 0) {

        double s = 0, t = 0, f = 0, ss;

        try {

            ResultSet rs = Database1.getStm().executeQuery("select * from customer_info where room_no = '" + cbmRn.getSelectedItem().toString() + "'");
            while (rs.next()) {
                txtFN.setText(rs.getString("first_name"));
                txtLN.setText(rs.getString("last_name"));
                Date date = rs.getDate("arrival_date");
                int da = date.getDate();
                int mo = date.getMonth() + 1;
                int ye = date.getYear() + 1900;
                txtDay.setText(da + "");
                txtMon.setText(mo + "");
                txtYear.setText(ye + "");


                CDate();
                getAllRecords();
                if (Ad > Dd) {
                    Dd = Dd + 30;
                    Dm = Dm - 1;
                }
                if (Am > Dm) {
                    Dm = Dm + 12;

                }
                d3 = Dd - Ad;
                m3 = Dm - Am;

                day = "" + d3;
                month = "" + m3;

                lblTD.setText(day);

                ResultSet rs2 = Database1.getStm().executeQuery("select * from room_info where room_no = '" + cbmRn.getSelectedItem().toString() + "'");
                if (rs2.next()) {
                    lblRPN.setText(rs2.getString("rate_per_night"));
                    s = rs2.getDouble("rate_per_night");
                }
                t = Double.parseDouble(day);
                f = t * s;
                String q = String.valueOf(f);
                lblRB.setText(q);

            }
        } catch (Exception e1) {
            e1.printStackTrace();
        }
        double fb = totalBill("food_bill");
        double sb = totalBill("service_bill");
        double ob = totalBill("other_bill");

        lblFB.setText(fb + "");
        lblSB.setText(sb + "");
        lblOB.setText(ob + "");

        double tBill = fb + sb + ob + f;
        lblTO.setText(tBill + "");
        lblDue.setText(tBill + "");
        txtPaid.setText("0.0");

    }
}//GEN-LAST:event_cbmRnItemStateChanged
    public void billPaid() {
        double tBill = Double.parseDouble(lblTO.getText());
        double tPaid = Double.parseDouble(txtPaid.getText());
        if (tPaid > 0) {
            double due = tBill - tPaid;
            lblDue.setText(due + "");
        }
    }

    private double totalBill(String s) {
        double tt = 0.0;

        try {
            ResultSet rs = Database1.getStm().executeQuery("select * from charge_info where room_no = '" + cbmRn.getSelectedItem().toString() + "' and last_name = '" + txtLN.getText().toString() + "' ");
            List<Double> plist = new ArrayList<Double>();
            while (rs.next()) {
                plist.add(rs.getDouble(s));
            }
            Double[] pl = new Double[plist.size()];
            plist.toArray(pl);
            for (int i = 0; i < pl.length; i++) {
                tt += pl[i];
            }

        } catch (Exception e) {
        }
        return tt;
    }
private void cbmRnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmRnActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cbmRnActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    clear();
}//GEN-LAST:event_jButton1ActionPerformed

private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
// TODO add your handling code here:


//    Main.checkOutFlag = true;
    int AA = JOptionPane.showConfirmDialog(rootPane, "Do you want to check Out " + Fn + "?");
    if (AA == 0) {
        double D = Double.parseDouble(lblDue.getText());
        String Ad1 = txtDay2.getText();
        String Am1 = txtMon2.getText();
        String y1 = txtYear2.getText();

        String cdate = y1 + "-" + Am1 + "-" + Ad1;
        String Vac = "Vacant";
        if (D == 0.0) {
            getAllRecords();
            setDate();

            try {
                Database1.getStm().executeUpdate("update total_info set no_of_days = '" + Td + "', total_room_bill = '" + Rb + "', total_food_bill = '" + Tf + "', total_service_bill = '" + Ts + "' , total_other_bill = '" + To + "', total_bill_paid = '" + Tp + "', departure_date = '" + cdate + "' where room_no = '" + cbmRn.getSelectedItem().toString() + "' ");
                Database1.getStm().executeUpdate("update room_info set Status='" + Vac + "' where room_no = '" + cbmRn.getSelectedItem() + "'");
                Database1.getStm().executeUpdate("delete from customer_info where room_no = '" + cbmRn.getSelectedItem().toString() + "'");
                this.dispose();
                JOptionPane.showMessageDialog(rootPane, "Checkout successfully completed");
                System.out.println("Yahoo!");
            } catch (Exception ex1) {
                ex1.printStackTrace();
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Total bill didn't paid!");
        }
    }




}//GEN-LAST:event_btnOkActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtYearActionPerformed

private void txtMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtMonActionPerformed

private void btnPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaidActionPerformed
// TODO add your handling code here:
    double tp = Double.parseDouble(txtPaid.getText().toString());
    if (tp > 0.0) {
        billPaid();
        try {
            Database1.getStm().executeUpdate("update customer_info set total_food_bill = '" + lblFB.getText().toString() + "', total_service_bill = '" + lblSB.getText().toString() + "', total_other_bill = '" + lblOB.getText().toString() + "', total_bill_paid = '" + txtPaid.getText().toString() + "' where room_no = '" + cbmRn.getSelectedItem().toString() + "'");
            JOptionPane.showMessageDialog(rootPane, "Bill successfully paid");
            btnPaid.setVisible(false);
        } catch (Exception ex1) {
            ex1.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(rootPane, "You must input total bill");
        txtPaid.requestFocus();
    }
}//GEN-LAST:event_btnPaidActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPaid;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox cbmRn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDue;
    private javax.swing.JLabel lblFB;
    private javax.swing.JLabel lblOB;
    private javax.swing.JLabel lblRB;
    private javax.swing.JLabel lblRPN;
    private javax.swing.JLabel lblSB;
    private javax.swing.JLabel lblTD;
    private javax.swing.JLabel lblTO;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtDay2;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtLN;
    private javax.swing.JTextField txtMon;
    private javax.swing.JTextField txtMon2;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtYear;
    private javax.swing.JTextField txtYear2;
    // End of variables declaration//GEN-END:variables
}
